server:
  port: 8080

logging:
  level:
    .: error
    org.springframework: ERROR
    com.eny: DEBUG

spring:
  data:
    mongodb:
      port: 27017
      database: sensorDataDb
      username: consumerUser
      password: password
  kafka:
    bootstrap-servers: localhost:9092, localhost:9093, localhost:9094

eureka:
  client:
    service-url:
      defaultZone: localhost:8761/eureka/