server:
  port: 8080

logging:
  level:
    ROOT: DEBUG

spring:
  data:
    mongodb:
      port: 27017
      database: sensorDataDb
      username: consumerUser
      password: password
  kafka:
    bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
feign:
  client:
    device-service:
      url: localhost:8084